# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(default='#', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(default='00 0 0000 0000', max_length=12),
        ),
    ]
